language: python
python: '3.6'
services:
  - docker

install:
  - >
    docker build \
      --tag yuma123/yangcli:2.11 \
      --tag yuma123/yangcli:latest \
      ./yangcli/

  - pip install --upgrade pip setuptools
  - pip install robotframework

script:
  - robot ./yangcli/test/
